### PR TITLE
Renaming in maps editor #1087

### PR DESCRIPTION
**Pull request by finnfiddle**
#1087
- [ ] **Update release notes if necessary**

### CODE REVIEW

**Comment by finnfiddle** [comment]
@kardan @gabemart @nadiagorchakova @tangrammer  I made it so that if it fails to save for some reason (like being offline) then it will show a save button and retry over and over with longer intervals each time. if you want think it should work another way let me know

**Comment by kardan** [comment]
I was thinking that I was assigned as reviewer to, hence tested it out. When I create a new map I directly get a modal asking me if I want to leave the page. This is in Chrome. That looks like a bug to me

**Comment by gabemart** [comment]
There's an existing issue with dashboards that makes the autosave a bit weird. 

If you create a visualisation and don't give it a name, it autosaves as "untitled visualisation".

But if you create a dashboard and don't give it a name, the autosave doesn't trigger until you give it a name, which is a bit unintuitive for the user.

So even though the behaviour (dashboards won't save without an explicit title) isn't introduced by this pr, I think we should fix it before we merge this

**Comment by finnfiddle** [comment]
I made the changes requested

**Comment by gabemart** [comment]
👍 lgtm

**Pull request merged**
