### PR TITLE
No prompt for unsaved changes #878

### PR DESCRIPTION
**Pull request by finnfiddle**
#878

- [ ] **Update release notes if necessary**

### CODE REVIEW

**Comment by gabemart** [comment]
@finnfiddle this works well but can you help me understand why `NavigationPrompt` takes a function as a child rather than the bare components? I.e. why we use `return this.props.children()` instead of `return this.props.children`?

**Comment by finnfiddle** [comment]
@gabemart youre right it was unnecessary - Ive changed it

**Comment by gabemart** [comment]
Ah ok just wanted to check 👍

**Comment by gabemart** [comment]
LGTM 👍

**Pull request merged**
