### PR TITLE
Issue/2127 rqg js

### PR DESCRIPTION
**Pull request by iperdomo**
- Fixes spec definition (metadata is a `vector` not a `map`)
  - An error in this problematic spec was hidden behind a `(catch Exception _)` . The function instrumentation was complaining and reporting a misleading error :cry: 

- The main change is to help a user write less code when by converting `rqg` columns to a JS object automatically, __before__ executing the user's code. We do it by enhancing the _adapter_ that was converting column names -> column title and adding a key `__rgq__` to the `row` object.  This key has an array of all columns of type `rqg`. The transformation function loops that array (if present) and calls `JSON.parse()` on those column's values.

- The `row` object passed to the JS context was previously a Clojure immutable datastructure, because we're mutating those `rqg` keys, we convert that object in to a mutable `HashMap` before passing it to the JS code.

### CODE REVIEW

**Comment by tangrammer** [comment]
@iperdomo BTW, do we have new tests for this new js functionality extensión?

**Comment by iperdomo** [comment]
@tangrammer we don't have tests. no

**Comment by tangrammer** [comment]
> @tangrammer we don't have tests. no

https://github.com/akvo/akvo-lumen/pull/2703 one here

**Comment by tangrammer** [comment]
we can merge the unit test later if we think so

**Pull request merged**
