### PR TITLE
Object.values undefined on old browsers #1346

### PR DESCRIPTION
**Pull request by finnfiddle**
#1346

- [ ] **Update release notes if necessary**

### CODE REVIEW

**Comment by gabemart** [comment]
@finnfiddle Perhaps we should also add a `'values' in Object` test to the `browserSupported` const?

**Comment by finnfiddle** [comment]
@gabemart whats wrong with the current approach?

**Comment by gabemart** [comment]
@finnfiddle we conditionally load the combined polyfill bundle based on the `browserSupported` boolean

````
  const browserSupported = Boolean(
    'fetch' in window &&
    'assign' in Object &&
    'Intl' in window &&
    'filter' in Array.prototype
  );
````
 This pr updates the polyfill bundle to include the object values polyfill, but doesn't update the `browserSupported` const. If a browser supports `fetch`, `assign`, `Intl` and `filter`, but doesn't support `Object.values`, the polyfill bundle won't be loaded

**Comment by finnfiddle** [comment]
@gabemart ok got it

**Pull request merged**
