### PR TITLE
improve legend for bubble charts (Connect #1839)

### PR DESCRIPTION
**Pull request by finnfiddle**
- [ ] **Update release notes if necessary**

### CODE REVIEW

**Comment by finnfiddle** [comment]
Here is a screenshot of how it will look with these changes 
screen shot 2018-12-06 at 4 14 48 pm

If @janagombitova approves of the changes then we'll need translations from @loicsans and @tangrammer  - you can see in the code what I added

**Comment by janagombitova** [comment]
@finnfiddle can I test this somewhere? dark-test? if not from the screen shot here are some comments: 
- it seems you selected Adm1_name as the bucket column, thus the variable that makes the bubbles render and gives them distinct colours. To me this column title should then be shown above the different colour specs in the legend, not above the size - like we have with bar charts 
- I then assume the size is based on First_fl_1-mean. But because the Adm1.. is above it is seems like it is the title of the size, but it is not. 
- Is it possible to distinguish the two pieces of information - what defines the bubble colours and what defines the bubble sizes as two pieces of info in the legend? is there a visual way to indicate the size in the legend? 
- I assume Salim can also edit the Legend titles, right, like we have with the bar charts?

Overall, I was hoping for something like this. Perhaps ping @Kiarii and @loicsans to see if you three can come up with a nice solution. 

screen shot 2018-12-06 at 16 19 26

**Comment by finnfiddle** [comment]
good comments @janagombitova

**Comment by finnfiddle** [comment]
ok how about this @janagombitova?
screen shot 2018-12-10 at 11 41 15 am

**Comment by janagombitova** [comment]
Uuuu that looks much more organised and also informative in my opinion. I like. 

I assume Salim will be able to change the name in both legend items, right? 

And one thing that can use more love is alignment and scale. 
- Can the two items be better aligned? Not sure how though, but this layout is a bit off in my view. 
- And can you make the size legend a bit less prominent, smaller perhaps? It is quite in your face now. How will it work if this visualisation is added to a dashboard and does not get a lot of space on the canvas?

**Comment by finnfiddle** [comment]
ok how about this now @janagombitova?
screen shot 2018-12-10 at 12 15 49 pm

**Comment by janagombitova** [comment]
I think it is a good solution to get out and hear what users think! Well done 👍

**Pull request merged**
