### PR TITLE
[#220] dashboard editor text entities

### PR DESCRIPTION
**Pull request by gabemart**
#220

### CODE REVIEW

**Comment by jonase** [comment]
This seems to work as expected 👍 

I noticed another possible problem in safari but perhaps that should be treated as a separate issue:

image

**Comment by jonase** [comment]
and in firefox:

image

**Comment by gabemart** [comment]
@jonase I agree, I think we should treat the title issue as a separate issue. I will open one and self assign

**Comment by jonase** [comment]
👍 then I'll merge this one.

**Pull request merged**
