### PR TITLE
Issue 2963/hide introjs in visualization editor

### PR DESCRIPTION
**Pull request by marvinkome**
- [ ] **Update release notes if necessary**

- Stop showing introjs step in visualization
- Render introjs only once

### CODE REVIEW

**Comment by tangrammer** [comment]
@marvinkome could you point the lines changed that are related to:

1- Stop showing introjs step in visualization
2 -Render introjs only once

In relation to point 1, does it mean that if a user clicks in this link (https://lumen.akvotest.org/visualisation/5fa11b66-bb83-4581-8c45-4c85bbc8ab32) is not going to have the introjs? (so trying to edit directly the viz without going through library step/screen )

**Comment by tangrammer** [comment]
PS: I like the new hook design! 🚀 
PS2: do we really need these lines https://github.com/akvo/akvo-lumen/blob/af9b8a0e21a3659f6a93d1aacc238dfa9e592f50/client/src/components/dataset/DatasetTableV2.jsx#L41-L55 ? they looks like very introjs internal details 🤔

**Comment by marvinkome** [comment]
> @marvinkome could you point the lines changed that are related to:
> 
> 1- Stop showing introjs step in visualization
> 2 -Render introjs only once
> 
> In relation to point 1, does it mean that if a user clicks in this link (https://lumen.akvotest.org/visualisation/5fa11b66-bb83-4581-8c45-4c85bbc8ab32) is not going to have the introjs? (so trying to edit directly the viz without going through library step/screen )

Introjs was showing in visualization before it was called twice. So when you close the first one (it destroys the first instance of introjs, but other instances are still loaded). So when you go to visualization screen and press ENTER, it continues the intro of other instances

**Comment by marvinkome** [comment]
> PS: I like the new hook design! 🚀
> PS2: do we really need these lines?
> 
> https://github.com/akvo/akvo-lumen/blob/af9b8a0e21a3659f6a93d1aacc238dfa9e592f50/client/src/components/dataset/DatasetTableV2.jsx#L41-L55
> 
> they looks like very introjs internal details 🤔

Yes. IntroJS doesn't work with React out of the box. So with the onbeforechange we dynamically point to the element when it's present in the DOM

**Comment by tangrammer** [comment]
> > PS: I like the new hook design! 🚀
> > PS2: do we really need these lines?
> > https://github.com/akvo/akvo-lumen/blob/af9b8a0e21a3659f6a93d1aacc238dfa9e592f50/client/src/components/dataset/DatasetTableV2.jsx#L41-L55
> > 
> > they looks like very introjs internal details 🤔
> 
> Yes. IntroJS doesn't work with React out of the box. So with the onbeforechange we dynamically point to the element when it's present in the DOM

then why don't we move this logic to a proper file instead of being inside DatasetTableV2 ?

**Pull request merged**
