### PR TITLE
Remove aggregation/query `donut` support

### PR DESCRIPTION
**Pull request by tangrammer**
- [ ] **Update release notes if necessary**

### CODE REVIEW

**Comment by tangrammer** [comment]
@gabemart as we chatted previously I've remove the BE legacy code for aggregation `donut`

**Comment by gabemart** [comment]
@tangrammer there was one place where the "donut" agg was invoked so I pushed a small commit to change it to pie (which is what we do with line/area, so it's what I should have done in the first place)

**Comment by tangrammer** [comment]
@gabemart ups, I missed this place, good catch!

**Comment by gabemart** [comment]
👍 let's merge

**Pull request merged**
