### PR TITLE
[#2741] - allows to select all column during combine columns and generate geopoints

### PR DESCRIPTION
**Pull request by marvinkome**
- [ ] **Update release notes if necessary**

### CODE REVIEW

**Comment by iperdomo** [comment]
@marvinkome did you checked the expected logic explained in the issue?

> For transformations when 2 or more columns are needed, when Salim selects a column from a RQG, we should allow him to select the second column only from the same group. If he selects the first column from a non-RQG, he should be able to select the 2nd column from any group besides the RQGs.

For RQG, we filter by columns in that group. For non-RQG all columns in non-RQG data groups.

**Comment by marvinkome** [comment]
I thought the logic is only needed when we have support for RQG?

**Comment by iperdomo** [comment]
> I thought the logic is only needed when we have support for RQG?

That it's an option, but why wait? or are we going to log a different issue to support that logic? It feels that we can fix it right away? What do you think?

**Comment by marvinkome** [comment]
Right now we don't know if it's a RQG or not

**Comment by janagombitova** [comment]
Just chipping in. I agree with the notion `why wait`. But if we are waiting because more work needs to be done to know which group is repeated (as we do not have that data yet) then I suggest we push out this change. And in another effort ensure we know which group is repeated and enforce the limitation for RQGs.

**Comment by janagombitova** [comment]
@marvinkome and @iperdomo what is the status of this change?

**Pull request merged**
