### PR TITLE
Remove showing pricing plan and limit (Connect #1569)

### PR DESCRIPTION
**Pull request by tangrammer**
- [ ] **Update release notes if necessary**

### CODE REVIEW

**Comment by tangrammer** [comment]
@janagombitova would you like also to remove backend endpoints related to this screen?

BTW: could you confirm me the details that you want to keep in this `resources` screen?
here the current WIP state ...

**Comment by janagombitova** [comment]
@tangrammer that is perfect! Would it be possible to also count number of dashboards? :) or is that a different issue?

**Comment by tangrammer** [comment]
yep, 👌 dashboard count could be tracked in this issue too

**Comment by tangrammer** [comment]
current view state: 
screen shot 2018-10-26 at 09 54 28

@janagombitova I've changed a bit the titles, could you ckeck final image changes ^^ ?

**Comment by janagombitova** [comment]
Looking good!

**Comment by tangrammer** [comment]
@janagombitova ... so merged now :)

**Pull request merged**
