### PR TITLE
[#2362] Uppdate to Java 11

### PR DESCRIPTION
**Pull request by kardan**
This PR is only for the production docker-container. The dev one is using

https://github.com/akvo/akvo-dockerfiles/blob/master/lumen-backend-dev/Dockerfile#L3
-> 
https://hub.docker.com/layers/clojure/library/clojure/lein-2.9.1/images/sha256-0abe12c86b7eb9767c69b656a5fcc237fb385cb5e733318ed8f1288bef6235f9

### CODE REVIEW

**Comment by kardan** [comment]
Let's not merge this before https://github.com/akvo/akvo-lumen/pull/2365

**Comment by dlebrero** [comment]
It makes me a little bit uneasy to not use the same JDK version in the dev env. Should we do that work also in this branch?

**Comment by tangrammer** [comment]
Develop build is broken on cypress  tests https://dashboard.cypress.io/#/projects/wazc6q/runs/4111/specs

**Comment by tangrammer** [comment]
https://api.travis-ci.org/v3/job/592460322/log.txt
```
backend_1                   | Error: Could not create the Java Virtual Machine.
backend_1                   | Error: A fatal exception has occurred. Program will exit.
```

**Comment by tangrammer** [comment]
``` backend_1                   | Unrecognized VM option 'PrintGCDateStamps' ```

**Pull request merged**
