### PR TITLE
[#592] Use 20-color default palette for maps, bar and pie visualisations

### PR DESCRIPTION
**Pull request by gabemart**
#592

- [ ] Update release notes
- [ ] Test plan | Unit test | Integration test
- [ ] Copyright header
- [ ] Code formatting
- [ ] Documentation

### CODE REVIEW

**Comment by gabemart** [comment]
I will add some grey tones to the palette as per #616

**Comment by gabemart** [comment]
Ready for review

**Comment by jonase** [comment]
:+1: lgtm

**Comment by mtwestra** [comment]
@gabe, Tested on Wolf Depredations dataset. Overall, works fine on bar and pie visualisations. One comment I would have is that the greys are now consecutive, which looks a little odd when they are used - see below.
screen shot 2017-03-07 at 11 58 53

Something seems strange with the maps, see below. A lot of the colours seem to default to black, somehow.
screen shot 2017-03-07 at 12 04 55

**Pull request merged**
