### PR TITLE
Add deployment docs in FAQs style

### PR DESCRIPTION
**Pull request by tangrammer**
- [ ] **Update release notes if necessary**

### CODE REVIEW

**Comment by tangrammer** [comment]
@iperdomo only a couple of things to add to this doc ...
first one: [flipping instances](https://github.com/akvo/akvo-lumen/blob/4b618cfa9e05f28bd7c3337a05a9d8d1cb184e5c/doc/faqs/deployment.org#how-we-can-flip-colors-flipping-instances)
second one: how can we ask for `test environment` active color? `ci/live-color.sh` doesn't receive any arg 🤔 ...

**Comment by tangrammer** [comment]
@iperdomo feel free to add any comment or fix to `deployment.org` file and i'll generate again the html version if you prefer ... I suppose that if we go ahead with this kind of orgmode doc style we'll need some kind of hook in ci build 🤔 to generate the html public version

**Comment by tangrammer** [comment]
@iperdomo added instructions to tag and release new deployments

**Comment by kardan** [comment]
@tangrammer what's the status on this issue, do we want to merge or does it need to be updated?

**Comment by tangrammer** [comment]
Closing the PR until having more agreements on how we could doc better

**Pull request closed without merging**
