### PR TITLE
[#1710] Reuse first migrated test database as template for all tests

### PR DESCRIPTION
**Pull request by tangrammer**
- [ ] **Update release notes if necessary**

### CODE REVIEW

**Comment by kardan** [comment]
On a newly started docker-compose en
```
$ docker-compose exec backend lein test :all
...
...
...
lein test akvo.lumen.utils.dev-emailer

lein test akvo.lumen.utils.local-error-tracker

lein test akvo.lumen.utils.local-server

lein test akvo.lumen.utils.logging-config

Ran 92 tests containing 607 assertions.
22 failures, 0 errors.
Tests failed
```

**Comment by iperdomo** [comment]
I executed
```
CI_COMMIT=local ./ci/build.sh

...
lein test :only akvo.lumen.lib.transformation-test/test-data-groups-transformations

FAIL in (test-data-groups-transformations) (transformation_test.clj:167)
Valid log
expected: (= (quote ({:rnum 1, :c1 "A   ", :c2 "b   ", :c3 "c"})) (get-data *tenant-conn* {:table-name (:table-name data-group)}))
  actual: (not (= ({:rnum 1, :c1 "A   ", :c2 "b   ", :c3 "c"}) ({:rnum 1, :c1 "a   ", :c2 "b   ", :c3 "c"})))
...
Ran 46 tests containing 401 assertions.
1 failures, 0 errors.
Tests failed.
```

I cleared the docker environment, then start it again: `docker-compose up --build -d` and execute the tests

```
$ docker-compose exec backend run-as-user.sh lein do test :functional
...
Ran 46 tests containing 401 assertions.
0 failures, 0 errors.
```

After a new dev environment, the same:
```
docker-compose exec backend run-as-user.sh lein test :all
...
Ran 92 tests containing 607 assertions.
0 failures, 0 errors.

```

After that successful run:
```
docker-compose exec backend run-as-user.sh lein test :all
Ran 92 tests containing 607 assertions.
18 failures, 0 errors.
```

This suggests:
* @kardan is not completely tearing down the environment `docker-compose down -v`
* Our tests are not *idempotent*

**Comment by kardan** [comment]
More steps from my side
Prepare
`
docker-compose down -v
docker-compose up -d --build
`
Run some tests
`
$ docker-compose exec backend lein test :all
...
FAIL in (test-data-groups-transformations) (transformation_test.clj:167)
Valid log
expected: (= (quote ({:rnum 1, :c1 "A   ", :c2 "b   ", :c3 "c"})) (get-data *tenant-conn* {:table-name (:table-name data-group)}))
actual: (not (= ({:rnum 1, :c1 "A   ", :c2 "b   ", :c3 "c"}) ({:rnum 1, :c1 "a   ", :c2 "b   ", :c3 "c"})))
08:27:05.034 [clojure-agent-send-off-pool-2] INFO  akvo.lumen.db.job-execution - vacuum-table ds_bf35d2d2_2627_4b57_beea_6fb13558e72e Elapsed time: 26.813308 msecs
08:27:07.114 [clojure-agent-send-off-pool-2] ERROR akvo.lumen.lib.transformation.engine - Failed to transform: Cannot delete column. It is used in the following visalisations: 'Visualisation', columns: null, execu
tion-log: null, data: (["5fbb725b-dda9-43ac-acbe-4139e6f0fdef" "Visualisation" #{"c1"}])
08:27:07.116 [clojure-agent-send-off-pool-2] INFO  akvo.lumen.fixtures - Cannot delete column. It is used in the following visalisations: 'Visualisation'
`

`
$ docker-compose exec backend run-as-user.sh lein do test :functional
...
Ran 46 tests containing 401 assertions.
18 failures, 0 errors.
Tests failed.
`

**Comment by iperdomo** [comment]
We're not going to merge this branch for now

**Pull request closed without merging**
