### PR TITLE
[#242] Make dataset permalinks work properly

### PR DESCRIPTION
**Pull request by jonase**

### CODE REVIEW

**Comment by jonase** [comment]
@gabemart please hold the merge on this one.. there are some subtle issues with pending transformations that needs to be resolved

**Comment by gabemart** [comment]
@jonase The library container now makes an API call every time it is mounted, e.g. it will refetch the library if you open a dataset, then return to the library. This is the intended behaviour, correct? Because the library call only fetches metadata about the entities, so we can afford to refetch on every mount?

**Comment by jonase** [comment]
@gabemart that was my thinking, yes. We could be smarter as well and check if all the entity types are empty, and only fetch if that's the case.. but perhaps that's an optimisation for the future?

**Comment by gabemart** [comment]
@jonase yep :+1:

**Pull request merged**
