### PR TITLE
[#447] Add release notes to PR template

### PR DESCRIPTION
**Pull request by jonase**
- [ ] Test plan | Unit test | Integration test
- [ ] Copyright header
- [ ] Code formatting
- [ ] Documentation

### CODE REVIEW

**Comment by punchagan** [comment]
We (RSR team) have started doing this, and it's pretty useful when trying to get release notes before a release. 

One problem that we face, though, is that PRs tend to have conflicts a lot more than before because of the  RELEASE_NOTES.md file.  Not sure there's a good way to work around this.

**Comment by jonase** [comment]
@punchagan Thanks, Good point. 

These merge conflicts should be easy to resolve since we're only adding lines, never changing what someone else previously added so the merge strategy should be trivial.

So if we merge develop into our feature branch before we open the PR we will often see a merge conflict in `RELEASE_NOTES.md` but my hope is that with some experience we'll be able to quickly resolve these.

(Maybe there's even a `git merge -s <strategy>` to only add new lines?)

**Comment by punchagan** [comment]
If PRs are getting merged quickly after they are opened, it shouldn't be a big problem. But, often when a handful of PRs are open, some of them conflict the others, and they can't be merged from the GitHub UI without first fixing the PR.

**Comment by jonase** [comment]
@punchagan yeah, I can see that. Let's see if it causes more problems than it solves. I can't think of a good solution right now, but I like the idea that the person who's in charge of the feature/bug-fix updates the release notes.

Are you thinking of doing something else in RSR?

**Comment by punchagan** [comment]
Yes, it is indeed a very nice idea and I like it too.  But, it's sometimes annoying when you are reviewing a PR and you have to resolve this 'stupid' conflict.  Just on the look out for other ideas, to work around this.

**Pull request merged**
