### PR TITLE
Add group column to lumen dataset view (Only flow datasets)

### PR DESCRIPTION
**Pull request by tangrammer**
- [ ] **Update release notes if necessary**
Relates #2437 

This PR only does what the title states. Following PRs will contain the logic to avoid collisions on duplicated questions names and javascript execution 

Pay attention that we add 2 groups besides the flow questions groups. One called "Survey details" containing : `'identifier', 'instance_id', 'display_name', 'submitter', 'submitted_at', 'surveyal_time', 'device_id'.` The other called 'Transformations' that will contain the columns resulted of a lumen transformation

PS: We need still to agree on having these 2 new groups @janagombitova  @kardan 

Screen Shot 2019-11-28 at 09 11 53

Screen Shot 2019-11-28 at 09 12 03

### CODE REVIEW

**Comment by iperdomo** [comment]
Hi,

>  "Survey details"

Why *Survey* if the user imported a *Form* ?

**Comment by tangrammer** [comment]
@iperdomo good point!

**Comment by janagombitova** [comment]
`Transformations` are brilliant. `Form details` can be deceiving as is it the details of the form/questionnaire or of the submissions. We use a lot of confusing language in Flow/Lumen. But in Flow data exports we call these first columns 'Metadata' as it is the metadata about the submissions. So let's use that for consistency.

**Comment by kardan** [comment]
As "Form metadata" ?

**Comment by janagombitova** [comment]
No just `Metadata`

**Comment by janagombitova** [comment]
We can always reiterate later

**Pull request merged**
